version: 1.0.{build}
image: Visual Studio 2019
skip_commits:
  message: /docs|Merge pull request.*/
build_script:
- cmd:  dotnet build Anabasis.MethodCache.Fody.sln --configuration Release /property:Version=%APPVEYOR_BUILD_VERSION% 
test: off
test_script:
- cmd: |
    cd %APPVEYOR_BUILD_FOLDER%
    dotnet test Anabasis.MethodCache.Test\Anabasis.MethodCache.Test.csproj --configuration Release --no-build --no-restore
    dotnet test Anabasis.MethodCache.AspNet.Tests\Anabasis.MethodCache.AspNet.Tests.csproj --configuration Release --no-build --no-restore
deploy:
  provider: NuGet
  api_key:
    secure: zuIMF/Jd5yeqbYdq9HDfTniovjEbGuRKqkBO6KrZpCiR/gjfqAgbSWhcp9htTzhb
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master