name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags for this build'
jobs:
  publish:
    name: Build, Test, Pack & Release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Anabasis.MethodCache.Fody.sln
    - name: Build
      run: dotnet build Anabasis.MethodCache.Fody.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test Anabasis.MethodCache.Fody.sln --verbosity normal
    - name: publish Anabasis.MethodCache
      uses: drusellers/publish-nuget@v3
      with:
       project-file-path: Anabasis.MethodCache/Anabasis.MethodCache.csproj
       version: 1.0.${{ github.run_number }}
       package-name: Anabasis.MethodCache.Fody
       nuget-key: ${{secrets.NUGET_KEY}}
    - name: publish Anabasis.MethodCache.AspNet
      uses: drusellers/publish-nuget@v3
      with:
       project-file-path: Anabasis.MethodCache.AspNet/Anabasis.MethodCache.AspNet.csproj
       version: 1.0.${{ github.run_number }}
       package-name: Anabasis.MethodCache.AspNet
       nuget-key: ${{secrets.NUGET_KEY}} 